version: '3.2'

services:
  app:
    image: mantesso/express-app:ex_3.1
    ports:
      - 8080:8080

  watchtower:
    image: containrrr/watchtower
    environment:
      - WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
