version: '3.8'

services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000

  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=1234
    depends_on:
      - db

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      - POSTGRES_PASSWORD=1234
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis:7.2.5-alpine
    ports:
      - "6379:6379"
