version: '2.1'

services:
  frontend:
    image: example-frontend
    ports:
      - 5000:5000

  backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.2.5-alpine
    ports:
      - "6379:6379"
